// SPDX-FileCopyrightText: 2026 Arthur Jean
// SPDX-License-Identifier: GPL-3.0-or-later

#![cfg_attr(test, allow(clippy::unwrap_used, clippy::expect_used, clippy::panic))]

//! Entry point of the hardware daemon.
//!
//! Refuses to run as root, probes the machine, takes what ownership it can and
//! serves the local socket. Every failure path exits with a diagnostic instead
//! of a panic.

use std::process::ExitCode;

use kori_core::lighting::{Brightness, LightingProgram, Rgb};
use kori_core::{KRAKEN_BASE, RGB_CONTROLLER};
use kori_daemon::rgb_probe::ProbeScope;
use kori_daemon::state::Daemon;
use kori_daemon::{DAEMON_VERSION, Paths, Server};
use kori_hardware_linux::SysfsRoot;

fn main() -> ExitCode {
    match run() {
        Ok(()) => ExitCode::SUCCESS,
        Err(message) => {
            eprintln!("korid: {message}");
            ExitCode::FAILURE
        }
    }
}

const USAGE: &str = "\
Usage: korid [OPTIONS]

Options:
  --capabilities     Print the versioned capability record as JSON and exit.
                     Read-only: no socket is opened and no device is written.
  --rgb-probe        The same record, with the RGB controller's topology read
                     from the device. Asks the controller what it is; sends no
                     color, no mode and no parameter, so it changes nothing.
  --rgb-write-probe  Sends lighting commands this product has not validated on
                     this firmware, one channel at a time, and refuses to start
                     without a typed confirmation. Prints the evidence record as
                     JSON on stdout.
      --with-effects   Also test the two animated candidates.
      --sweep-effects  Instead, sweep every effect speed and direction the
                       Lighting screen can select, on the first channel only.
                       This is what evidences the selectable values.
      --restore HEX    Leave every channel on this color instead of off.
  --probe            The capability record with both devices asked what they
                     are. This is what re-records docs/capability-record.json,
                     because both topologies belong in it. Read-only: every
                     report it sends is a query.
  --lcd-probe        The same, for the Kraken's panel alone. Sends two query reports that carry no picture, no
                     brightness and no orientation, so it changes nothing. A
                     device with no panel answers the second one not at all,
                     which is how this tells the two apart.
  --lcd-write-probe  Sends solid frames this product has not validated on this
                     firmware, one color at a time, and refuses to start
                     without a typed confirmation. Prints the evidence record
                     as JSON on stdout.
  --version          Print the version and exit.
  --help             Print this message.
";

fn run() -> Result<(), String> {
    let arguments: Vec<String> = std::env::args().skip(1).collect();
    match arguments.first().map(String::as_str) {
        None => serve(),
        // Which devices are asked what they are is the only difference between
        // these four, so it is the only thing they say here.
        Some("--capabilities") => print_record(Ask::NEITHER),
        Some("--rgb-probe") => print_record(Ask::RGB),
        Some("--lcd-probe") => print_record(Ask::LCD),
        Some("--probe") => print_record(Ask::BOTH),
        Some("--rgb-write-probe") => rgb_write_probe(&arguments[1..]),
        Some("--lcd-write-probe") => lcd_write_probe(),
        Some("--version") => {
            println!("korid {DAEMON_VERSION}");
            Ok(())
        }
        Some("--help" | "-h") => {
            print!("{USAGE}");
            Ok(())
        }
        Some(unknown) => Err(format!("unknown argument {unknown}\n\n{USAGE}")),
    }
}

/// Which devices a capability run asks to describe themselves.
///
/// Asking is not free of consequence in the sense that matters here: it opens a
/// device node. Every report it then sends is a query that carries no color, no
/// mode, no picture and no parameter, so nothing an operator can see changes.
/// The distinction between "read sysfs" and "talk to the device" is still worth
/// keeping in the command line rather than hiding behind one flag.
struct Ask {
    rgb: bool,
    lcd: bool,
}

impl Ask {
    /// Read sysfs only: no socket, no device node.
    const NEITHER: Self = Self {
        rgb: false,
        lcd: false,
    };
    const RGB: Self = Self {
        rgb: true,
        lcd: false,
    };
    const LCD: Self = Self {
        rgb: false,
        lcd: true,
    };
    /// What re-records `docs/capability-record.json`: the committed artifact has
    /// to carry both topologies, and a record regenerated by a focused probe
    /// would drop the other device's evidence and read as a device that
    /// answered nothing.
    const BOTH: Self = Self {
        rgb: true,
        lcd: true,
    };
}

/// Emit the versioned capability record, with whatever the caller asked the
/// devices themselves.
///
/// Serial numbers are redacted so the output can be attached to an issue or
/// committed without publishing a device identifier.
/// The handle each ask hands back is dropped here: a read-only run wants the
/// evidence, not the device. Asking through [`kori_daemon::startup`] rather than
/// repeating its steps is what makes the record this prints the same record the
/// daemon starts from.
fn print_record(ask: Ask) -> Result<(), String> {
    let mut record = kori_hardware_linux::probe(&SysfsRoot::from_env());

    if ask.rgb {
        let _ = kori_daemon::startup::ask_rgb(&mut record);
    }

    if ask.lcd {
        let _ = kori_daemon::startup::ask_lcd(&mut record);
    }

    record.redact_serials();
    emit_json(&record, "capability record")
}

/// Everything both write probes do before and after the run itself.
///
/// The per-device lock is taken first and held for the whole run, so a probe and
/// the daemon can never address the same device at the same time. Refusing when
/// the daemon holds it is the point: two writers is the failure this product
/// exists to prevent.
///
/// `run` receives the device's sysfs path with the lock already held, opens
/// whatever it needs from there, and returns the record to print. That is the
/// only part the two probes do not share.
fn under_device_lock<R: serde::Serialize>(
    device: kori_core::DeviceId,
    run: impl FnOnce(&std::path::Path) -> Result<R, String>,
) -> Result<(), String> {
    refuse_root()?;

    let record = kori_hardware_linux::probe(&SysfsRoot::from_env());
    let sysfs_path = kori_hardware_linux::probe::device_path(&record, device)
        .ok_or_else(|| format!("{device} is not connected to this machine"))?;

    let paths = Paths::from_env();
    paths
        .ensure()
        .map_err(|error| format!("could not prepare {}: {error}", paths.runtime_dir.display()))?;
    let _lock = kori_daemon::ownership::acquire(&paths, device).map_err(|conflict| {
        format!(
            "another process owns {device} ({}). Stop korid and try again.",
            conflict.detail
        )
    })?;

    emit_json(&run(&sysfs_path)?, "probe record")
}

/// Run the lighting write probe against the connected controller.
fn rgb_write_probe(arguments: &[String]) -> Result<(), String> {
    let (scope, restore) = parse_rgb_probe_arguments(arguments)?;

    under_device_lock(RGB_CONTROLLER, |sysfs_path| {
        let node = kori_hardware_linux::usb::hidraw_node(sysfs_path);
        let (topology, link) = kori_hardware_linux::rgb::connect(node);
        let mut link = link.ok_or_else(|| {
            format!(
                "the controller did not answer: {}",
                topology
                    .channels
                    .reason()
                    .unwrap_or("no reason was recorded")
            )
        })?;

        kori_daemon::rgb_probe::run(
            &mut link,
            &mut kori_daemon::probe::Terminal,
            &topology,
            scope,
            restore,
        )
        .map_err(|refusal| refusal.to_string())
    })
}

fn parse_rgb_probe_arguments(
    arguments: &[String],
) -> Result<(ProbeScope, LightingProgram), String> {
    let mut scope = ProbeScope::FixedAndOff;
    let mut restore = LightingProgram::Off;
    let mut rest = arguments.iter();
    while let Some(argument) = rest.next() {
        match argument.as_str() {
            "--with-effects" => scope = ProbeScope::WithEffects,
            "--sweep-effects" => scope = ProbeScope::EffectSweep,
            "--restore" => {
                let value = rest
                    .next()
                    .ok_or_else(|| "--restore needs a six-digit color".to_string())?;
                restore = LightingProgram::Fixed {
                    color: Rgb::parse_hex(value).map_err(|error| error.to_string())?,
                    brightness: Brightness::new(60).map_err(|error| error.to_string())?,
                };
            }
            unknown => return Err(format!("unknown argument {unknown}\n\n{USAGE}")),
        }
    }
    Ok((scope, restore))
}

/// Run the frame write probe against the connected panel.
fn lcd_write_probe() -> Result<(), String> {
    under_device_lock(KRAKEN_BASE, |sysfs_path| {
        let node = kori_hardware_linux::usb::hidraw_node(sysfs_path);
        let (topology, link) = kori_hardware_linux::lcd::connect(Some(sysfs_path), node);
        let mut link = link.ok_or_else(|| {
            format!(
                "the panel is not reachable: {}",
                topology
                    .display
                    .reason()
                    .or_else(|| topology.bulk_node.reason())
                    .or_else(|| topology.hid_node.reason())
                    .unwrap_or("no reason was recorded")
            )
        })?;

        kori_daemon::lcd_probe::run(&mut link, &mut kori_daemon::probe::Terminal, &topology)
            .map_err(|refusal| refusal.to_string())
    })
}

/// This process never needs root, so it refuses it rather than accepting a
/// privilege it would not use.
///
/// One refusal for the whole binary: three copies said three different things
/// about the same rule, and the rule is the same whichever subcommand asked.
fn refuse_root() -> Result<(), String> {
    if rustix::process::geteuid().is_root() {
        return Err(
            "refusing to run as root. Install the udev rule and run this as your own user."
                .to_string(),
        );
    }
    Ok(())
}

fn emit_json(value: &impl serde::Serialize, what: &str) -> Result<(), String> {
    let json = serde_json::to_string_pretty(value)
        .map_err(|error| format!("could not encode the {what}: {error}"))?;
    println!("{json}");
    Ok(())
}

fn serve() -> Result<(), String> {
    refuse_root()?;

    let paths = Paths::from_env();
    let sysfs = SysfsRoot::from_env();

    paths
        .ensure()
        .map_err(|error| format!("could not create {}: {error}", paths.runtime_dir.display()))?;

    // Single instance is decided here, before sysfs is read and before any
    // device is asked for. The lock, not the socket, is the arbiter, and it is
    // released by the kernel if this process is killed.
    let _instance = kori_daemon::ownership::acquire_instance(&paths)
        .map_err(|conflict| format!("could not start: {}", conflict.detail))?;

    // Bound before the hardware is touched, so nothing is acquired by a
    // process that is about to exit, and before anything is printed, so the
    // banner cannot announce a socket that was never taken.
    let listener = kori_daemon::server::bind_socket(&paths.socket)
        .map_err(|error| format!("could not bind {}: {error}", paths.socket.display()))?;

    let daemon = Daemon::start(paths.clone(), &sysfs)
        .map_err(|error| format!("could not start: {error}"))?;

    let status = daemon.status();
    let locked = daemon.locked_devices();
    println!(
        "korid {DAEMON_VERSION} listening on {}, holding {} device lock{}",
        status.socket_path,
        locked.len(),
        if locked.len() == 1 { "" } else { "s" }
    );
    for device in &status.devices {
        println!(
            "  {} owned={} writable={}",
            device.id,
            device.owned,
            device.writable.len()
        );
    }
    if let Some(message) = status.config.recovery_message() {
        eprintln!("  {message}");
    }

    let server = Server::attach(listener, daemon);
    stop_on_signal(server.shutdown_handle())?;
    server.run();
    Ok(())
}

/// Turn a termination signal into the orderly shutdown the server implements.
///
/// Without this, `systemctl stop` kills the process outright and the server's
/// own teardown never runs: the ticker is not joined, a command in flight is not
/// allowed to finish, and the socket is left behind for the next start to clean
/// up. All three are already handled correctly on the shutdown path, which until
/// now nothing but a test could reach.
///
/// The signals are delivered to an ordinary thread rather than to a handler, so
/// what runs on receipt is normal code taking normal locks. A second signal is
/// not waited for: an operator who sends one is asking for the process to go,
/// and the kernel releases every lock this daemon holds whatever way it exits.
fn stop_on_signal(handle: kori_daemon::server::ShutdownHandle) -> Result<(), String> {
    use signal_hook::consts::{SIGINT, SIGTERM};

    let mut signals = signal_hook::iterator::Signals::new([SIGTERM, SIGINT])
        .map_err(|error| format!("could not install the signal handler: {error}"))?;

    std::thread::spawn(move || {
        if signals.forever().next().is_some() {
            handle.stop();
        }
    });
    Ok(())
}
